### ISSUE TITLE
Cant open the jar

### ISSUE THREAD

**Issue by FerbFloo** [ElVir-Software/minicraft-plus-online#2]
I get the issue:
```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at minicraft.saveload.Load.loadPrefs(Load.java:343)
	at minicraft.saveload.Load.<init>(Load.java:142)
	at minicraft.core.Game.main(Game.java:148)

```
right after opening the jar and seeing the spashscreen. got no problems with the original minicraft + jar.

(Apple Silicon M1 MacBook, if the platform is important)

**Comment by El-Virus** [comment]
Could you try deleting ~/.playminicraft/mods/Minicraft_Plus/Preferences.miniplussave?

**Comment by El-Virus** [comment]
As more than a month has passed by until this last comment, I'll be closing the issue for inactivity.
